name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: 'Architecture'
    labels:
      - 'architecture'
      - 'refactor'
  - title: 'Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
  - title: 'Security'
    labels:
      - 'security'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'documentation'
      - 'chore'
  default: patch

template: |
  ## What's Changed

  $CHANGES

  ## Installation

  Add ARCLogger to your Swift package dependencies:

  ```swift
  dependencies: [
      .package(url: "https://github.com/arclabs-studio/ARCLogger.git", from: "$RESOLVED_VERSION")
  ]
  ```

  ## Contributors

  $CONTRIBUTORS

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
